In [3]:
import numpy as np

In [4]:
tamanho_do_tabuleiro = 8

In [14]:
for i in range(5):
    s = np.random.randint(tamanho_do_tabuleiro, size=tamanho_do_tabuleiro)
    print(s)

[2 4 0 3 1 7 5 0]
[4 6 2 5 5 1 3 0]
[2 1 7 0 7 1 0 0]
[4 1 1 5 6 0 2 4]
[0 6 6 5 5 3 2 5]


## Extrai as coordenadas

In [26]:
def extrai_coordenadas_do_individuo(ind, tamanho_tabuleiro):
    lista_coordenadas = []
    for i in range(tamanho_tabuleiro):
        lista_coordenadas.append((i,ind[i]))
    return lista_coordenadas

In [27]:
s = np.random.randint(tamanho_do_tabuleiro, size=tamanho_do_tabuleiro)
s

array([0, 2, 2, 1, 6, 2, 0, 0])

In [29]:
coords_s = extrai_coordenadas_do_individuo(s,8)
coords_s

[(0, 0), (1, 2), (2, 2), (3, 1), (4, 6), (5, 2), (6, 0), (7, 0)]