In [3]:
import numpy as np

In [2]:
tamanho_populacao = 100
tamanho_tabuleiro = 8

In [5]:
np.random.seed(seed=43)

In [6]:
pop = []

for i in range(tamanho_populacao):
    ind = np.random.randint(tamanho_tabuleiro, size=tamanho_tabuleiro)
    pop.append(ind)
    
pop

[array([4, 0, 7, 1, 5, 2, 0, 3]),
 array([1, 3, 3, 2, 6, 6, 7, 0]),
 array([3, 7, 2, 3, 3, 1, 1, 7]),
 array([2, 3, 2, 3, 5, 4, 4, 0]),
 array([5, 4, 0, 4, 7, 0, 2, 4]),
 array([0, 1, 2, 0, 4, 4, 0, 4]),
 array([1, 7, 5, 4, 7, 0, 5, 0]),
 array([3, 2, 1, 3, 1, 5, 0, 6]),
 array([2, 2, 5, 5, 5, 0, 2, 3]),
 array([2, 7, 7, 5, 3, 6, 3, 2]),
 array([6, 2, 4, 2, 7, 3, 3, 6]),
 array([0, 3, 6, 5, 4, 7, 4, 5]),
 array([6, 3, 5, 3, 0, 3, 6, 5]),
 array([3, 2, 1, 6, 0, 0, 4, 6]),
 array([7, 5, 7, 4, 3, 7, 1, 3]),
 array([1, 5, 5, 0, 0, 3, 6, 1]),
 array([4, 6, 6, 4, 7, 3, 7, 1]),
 array([4, 5, 0, 4, 4, 7, 4, 3]),
 array([2, 1, 6, 7, 0, 3, 0, 1]),
 array([0, 1, 3, 4, 7, 5, 4, 5]),
 array([2, 0, 6, 0, 3, 4, 2, 2]),
 array([4, 4, 3, 1, 4, 2, 2, 4]),
 array([7, 2, 1, 3, 6, 4, 5, 5]),
 array([0, 3, 4, 2, 4, 7, 7, 1]),
 array([3, 2, 7, 7, 1, 3, 1, 6]),
 array([2, 1, 3, 6, 5, 2, 1, 4]),
 array([5, 0, 4, 2, 5, 6, 0, 4]),
 array([5, 5, 0, 0, 4, 6, 7, 6]),
 array([7, 0, 5, 2, 0, 7, 1, 1]),
 array([3, 1, 